VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  ["database1", "database2"].each_with_index do |name, i|
    config.vm.define name do |node|
      node.vm.box = "almalinux/9"
      node.vm.hostname = name
      node.vm.network "private_network", ip: "192.168.58.#{10 + i}"

      node.vm.network "forwarded_port", guest: 27017, host: 27017 + i
      node.vm.network "forwarded_port", guest: 3306, host: 3306 + i

      node.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
      end

      node.vm.synced_folder ".", "/vagrant", disabled: false
      #enable mongodb provisioning
      node.vm.provision "shell", path: "mongo_startup.sh"

      #enable mysql provisioning
      node.vm.provision "shell" do |s|

        s.env = {
          "MYSQL_SERVER_ID" => "#{i + 1}" #unique id for each vm
        }
        s.path = "mysql_startup.sh"
      end
    end
  end
end

