VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  ["database1", "database2"].each_with_index do |name, i|
    config.vm.define name do |node|
      node.vm.box = "almalinux/9"
      node.vm.hostname = name
      node.vm.network "private_network", ip: "192.168.58.#{10 + i}"

      node.vm.network "forwarded_port", guest: 27017, host: 27017 + i
      node.vm.network "forwarded_port", guest: 3306, host: 3306 + i

      node.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 2
      end

      node.vm.synced_folder ".", "/vagrant", disabled: false
      node.vm.provision "shell", path: "startup.sh"
    end
  end
end

